# Linear Algebra review

## Matrices and vectors

### Matrix : Rectangular array of numbers

$\begin{bmatrix}
1402 & 191 \\
1371 & 821 \\
949 & 1437 \\
147 & 1448 \\
\end{bmatrix}$


$4 \times 2$ Matrix

$\rightarrow \in \mathbb{R}^{4x2}$

행렬의 차원 : 행의 수 x 열의 수

### Matrix Elements (entries of matrix)

$A = \begin{bmatrix}
1402 & 191 \\
1371 & 821 \\
949 & 1437 \\
147 & 1448 \\
\end{bmatrix}$

$A_{i,j} = $ "i,j entry" in the i-th row, j-th column.

$A_{11} = 1402$

$A_{12} = 191$

$A_{32} = 1437$

$A_{41} = 147$

$A_{43} = ? $

### Vector: An n x 1 matrix.


$y = \begin{bmatrix}
460\\
232 \\
315 \\
178 \\
\end{bmatrix}$

$ y_i = $ i-th element

$y_1 = 460$

$y_2 = 232$

$y_3 = 315$

|  begin with 1-indexed    |  vs. | begin with 0-indexed  |
|----------------|------|-------------|
|$y = \begin{bmatrix}y_1\\y_2 \\y_3 \\y_4 \\ \end{bmatrix}$ | vs. | $y = \begin{bmatrix} y_0\\y_1\\y_2\\y_3\\ \end{bmatrix}$ |
<hr>

In [10]:
import numpy as np
y = np.array([460, 232, 315, 178])
print("y's shape :", y.shape)
print('y =', y)
print('y[0]=',y[0], ' y[3]=',y[3])

y's shape : (4,)
y = [460 232 315 178]
y[0]= 460  y[3]= 178


In [13]:
A = np.array([[1402,191],[1371,821],[949,1437],[147,1448]])
print("A's shape :", A.shape)
print('A =', A)
print('A[0][0]=',A[0][0], ' A[2][1]=',A[2][1])

A's shape : (4, 2)
A = [[1402  191]
 [1371  821]
 [ 949 1437]
 [ 147 1448]]
A[0][0]= 1402  A[2][1]= 1437


## Addition and Scalar multiplication

### Matrix Addition


$\begin{bmatrix}
1 & 0 \\
2 & 5 \\
3 & 1 \\
\end{bmatrix}
+ \begin{bmatrix}
4 & 0.5 \\
2 & 5 \\
0 & 1 \\
\end{bmatrix} =
\begin{bmatrix}
5 & 0.5 \\
4 & 10 \\
3 & 2 \\
\end{bmatrix}
$

$\begin{bmatrix}
1 & 0 \\
2 & 5 \\
3 & 1 \\
\end{bmatrix}
+ \begin{bmatrix}
4 & 0.5 \\
2 & 5 \\
\end{bmatrix} = ?
$

### Scalar Multiplication

$3 \times \begin{bmatrix}
1 & 0 \\
2 & 5 \\
3 & 1 \\
\end{bmatrix} = \begin{bmatrix}
1 & 0 \\
2 & 5 \\
3 & 1 \\
\end{bmatrix} \times 3 = \begin{bmatrix}
3 & 0 \\
6 & 15 \\
9 & 3 \\
\end{bmatrix} 
$

$\begin{bmatrix}
4 & 0 \\
6 & 3 \\
\end{bmatrix} / 4 = { 1 \over 4 } \times \begin{bmatrix}
4 & 0 \\
6 & 3 \\
\end{bmatrix} = \begin{bmatrix}
1 & 0 \\
1.4 & 0.75 \\
\end{bmatrix}
$

### Combination of Operands

$3 \times \begin{bmatrix}
1 \\
4 \\
2 \\
\end{bmatrix} +
\begin{bmatrix}
 0 \\
 0 \\
 5 \\
\end{bmatrix} -
\begin{bmatrix}
 3 \\
 0 \\
 2 \\
\end{bmatrix} / 3 = 
$

>

>

>

<hr>

In [17]:
A = np.array([[1,0],[2,5],[3,1]])
B = np.array([[4,0.5],[2,5],[0,1]])
C = A + B
print(A,"\n", B,"\n",C)

[[1 0]
 [2 5]
 [3 1]] 
 [[4.  0.5]
 [2.  5. ]
 [0.  1. ]] 
 [[ 5.   0.5]
 [ 4.  10. ]
 [ 3.   2. ]]


In [19]:
D = 3 * A
print(D)
E = A / 4
print(E)

[[ 3  0]
 [ 6 15]
 [ 9  3]]
[[0.25 0.  ]
 [0.5  1.25]
 [0.75 0.25]]


In [20]:
a = np.array([1,4,2])
b = np.array([0,0,5])
c = np.array([3,0,2])
d = 3 * a + b - c / 3
print(d)

[ 2.         12.         10.33333333]


## Matrix-vector multiplication

## Example

$\begin{bmatrix}
1 & 3 \\
4 & 0 \\
2 & 1 \\
\end{bmatrix}
\begin{bmatrix}
1 \\
5 \\
\end{bmatrix} =
$

### Details : 

$$ A \quad \quad  \times  \quad \quad \quad \quad x\quad \quad  =\quad \quad  y $$
>

>

>

$$ \text{mxn matrix}  \quad \quad  \quad\text{nx1 matrix}\quad  \quad \quad  \text{m-dimensional vector} $$
>

$y_i$ 를 얻으려면, $A$ 의 i-번째 행을 벡터 $x$ 의 요소들과 곱하고 합산합니다.

### Example

$\begin{bmatrix}
1 & 2 & 1 & 5 \\
0 & 3 & 0 & 4 \\
-1 & -2& 0 & 0 \\
\end{bmatrix}
\begin{bmatrix}
1 \\
3\\
2 \\
1\\
\end{bmatrix} =
$

>

>

>


House sizes : 

$2104\\
1416\\
1534\\
852$     $\quad \quad h_\theta(x) = -40 +0.25 x$

In Matrix

$\begin{bmatrix}
1 & 2104 \\
1 & 1416 \\
1 & 1534 \\
1 & 852 \\
\end{bmatrix}
\begin{bmatrix}
-40 \\
0.25 \\
\end{bmatrix} =
$


>

>


In [29]:
A = np.array([[1,3],[4,0],[2,1]])
b = np.array([1,5])
c = np.dot(A,b)
print(c)

G = np.array([2104, 1416, 1534, 852])
G = np.array([np.ones(4),G]).T
print(G)
d = np.array([-40, 0.25])
e = np.dot(G,d)
print(e)

[16  4  7]
[[1.000e+00 2.104e+03]
 [1.000e+00 1.416e+03]
 [1.000e+00 1.534e+03]
 [1.000e+00 8.520e+02]]
[486.  314.  343.5 173. ]


## Matrix-matrix multiplication


### Example


$\begin{bmatrix}
1 & 3 & 2 \\
4 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
1 & 3 \\
0 & 1 \\
5 & 2 \\
\end{bmatrix} =
$

$\begin{bmatrix}
1 & 3 & 2 \\
4 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
1  \\
0  \\
5  \\
\end{bmatrix} =
$

$\begin{bmatrix}
1 & 3 & 2 \\
4 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
 3 \\
 1 \\
 2 \\
\end{bmatrix} =
$

### Details : 

$$ A \quad \quad  \times  \quad \quad \quad \quad B\quad \quad  =\quad \quad  C $$
>

>

>

$$ \text{mxn matrix}  \quad \quad  \quad\text{nxo matrix}\quad  \quad \quad  \text{mxo-dimensional matrix} $$
>

행렬 C의 i-번째 열은 행렬 A와 행렬 B의 i-번째 열과의 곱으로 얻어진다. ($i=1,2,\cdots,o$)


### Example

$\begin{bmatrix}
1 & 3 \\
2 & 5 \\
\end{bmatrix}
\begin{bmatrix}
0 & 1 \\
3 & 2 \\
\end{bmatrix} =
$

$\begin{bmatrix}
1 & 3 \\
2 & 5 \\
\end{bmatrix}
\begin{bmatrix}
0  \\
3  \\
\end{bmatrix} =
$

$\begin{bmatrix}
1 & 3 \\
2 & 5 \\
\end{bmatrix}
\begin{bmatrix}
1 \\
 2 \\
\end{bmatrix} =
$

House sizes : 

$2104\\
1416\\
1534\\
852$     $\quad \quad \begin{array} |
                        1. & h_\theta(x) & = -40 +0.25 x \\
                        2. & h_\theta(x) & = 200 +0.1 x\\
                        3. & h_\theta(x) & = -150 +0.4 x 
                        \end{array}$

In Matrix x Matrix

$\begin{bmatrix}
1 & 2104 \\
1 & 1416 \\
1 & 1534 \\
1 & 852 \\
\end{bmatrix}
\begin{bmatrix}
-40 & 200 & -150 \\
0.25& -.1 & 0.4\\
\end{bmatrix} =
$


>

>

<hr>

In [30]:
A = np.array([[1,3,2],[4,0,1]])
B = np.array([[1,3],[0,1],[5,2]])
C = np.dot(A,B)
print(C)

H = np.array([[-40, 200, -150], [0.25, -.1, 0.4]])
J = np.dot(G,H)
print(J)

[[11 10]
 [ 9 14]]
[[486.  -10.4 691.6]
 [314.   58.4 416.4]
 [343.5  46.6 463.6]
 [173.  114.8 190.8]]


## Matrix multiplication properties

$A$ 와 $B$ 가 행렬일 때, 일반적으로 $ A \times B \ne B \times A $ (교환법칙이 성립하지 않는다)

e.g. 

$\begin{bmatrix}
1 & 1 \\
0 & 0 \\
\end{bmatrix}
\begin{bmatrix}
0 & 0 \\
2 & 0 \\
\end{bmatrix} =
\begin{bmatrix}
2 & 0 \\
0 & 0 \\
\end{bmatrix}
$

$\begin{bmatrix}
0 & 0 \\
2 & 0 \\
\end{bmatrix}
\begin{bmatrix}
1 & 1 \\
0 & 0 \\
\end{bmatrix}
 =
\begin{bmatrix}
0 & 0 \\
2 & 2 \\
\end{bmatrix}
$

$A$,$B$ 와 $C$ 가 행렬일 때, 일반적으로 $ A \times B \times C $ 는:


$D = B \times C$ 일 때, $ A \times D$.

$E = A \times B$ 일 때, $ E \times C$.

$ A \times D = E \times C$ (결합법칙이 성립한다)

#### 단위행렬(Identity Matrix)

$I$ 로 표시 (또는 $I_{n\times n}$).

단위행렬의 예:

| $2\times 2$ | $3\times 3$ | $4\times 4$ | 
|-------------|-------------|-------------|
|$\begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix}$ | $\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix}$ |$\begin{bmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{bmatrix}$ |

임의의 행렬 $A$에 대하여,
$A \cdot I = I \cdot A = A$

>

>
<hr>

In [38]:
A = np.array([[1,1],[0,0]])
B = np.array([[0,0],[2,0]])
AB = np.dot(A,B)
print(AB)
BA = np.dot(B,A)
print(BA)

[[2 0]
 [0 0]]
[[0 0]
 [2 2]]


In [39]:
I2 = np.eye(2)
print(I2)
I3 = np.eye(3)
print(I3)
print(np.dot(A,I2))
print(np.dot(I2,A))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1.]
 [0. 0.]]
[[1. 1.]
 [0. 0.]]


#### 전치 행렬( Matrix Transpose)

예:

$A = \begin{bmatrix}
1 & 2 & 0\\
3 & 5 & 9\\
\end{bmatrix} \quad A^T = \begin{bmatrix}
1 & 3 \\
2 & 5 \\
0 & 9 \\
\end{bmatrix} $

$A$ 가 $m \times n$ 행렬이고, $B = A^T$ 라면,
$B$ 는 $n \times m$ 행렬이며, $B_{ij} = A_{ji}$ 이다.

> 

>

In [40]:
A = np.array([[1,2,0],[3,5,9]])
print(A.T)

[[1 3]
 [2 5]
 [0 9]]


## Broadcasting
(m,1) + (1,) ~> (m, 1)

$$ \begin{bmatrix}
1 \\ 2 \\ 3 \\ 4
\end{bmatrix} + 100 \quad \Rightarrow \quad \begin{bmatrix}
1 \\ 2 \\ 3 \\ 4
\end{bmatrix} +  \begin{bmatrix}
100 \\ 100 \\ 100 \\ 100
\end{bmatrix}$$


(m, n) + (1, n) ~> (m, n)

$$ \begin{bmatrix}
1, 2, 3 \\ 4, 5, 6
\end{bmatrix} + \begin{bmatrix}
100, 200, 300 
\end{bmatrix} \quad \Rightarrow \quad 
\begin{bmatrix}
1, 2, 3 \\ 4, 5, 6
\end{bmatrix} + \begin{bmatrix}
100, 200, 300 \\
100, 200, 300 
\end{bmatrix}$$


(m, n) + (m, 1)  ~> (m, n)

$$ \begin{bmatrix}
1, 2, 3 \\ 4, 5, 6
\end{bmatrix} + \begin{bmatrix}
100 \\ 200
\end{bmatrix} \quad \Rightarrow \quad 
\begin{bmatrix}
1, 2, 3 \\ 4, 5, 6
\end{bmatrix} + \begin{bmatrix}
100, 100, 100 \\
200, 200, 200 
\end{bmatrix}$$
<hr>

In [1]:
import numpy as np

a = np.array([1,2,3,4])
# a = np.array([[1],[2],[3],[4]])
print(a, " + 100 = ", a+100)

b = np.array([[1,2,3],[4,5,6]])
c = np.array([100,200,300])
print(b.shape, " + ", c.shape, " = ", (b+c).shape)
print(b + c)

d = np.array([[100],[200]])
print(b.shape, " + ", d.shape, " = ", (b+d).shape)
print(b + d)

[1 2 3 4]  + 100 =  [101 102 103 104]
(2, 3)  +  (3,)  =  (2, 3)
[[101 202 303]
 [104 205 306]]
(2, 3)  +  (2, 1)  =  (2, 3)
[[101 102 103]
 [204 205 206]]


### 브로드케스팅 일반 원칙


$$ \text{ matrix } (m,n)  \quad +  -  *  / \quad (1,n) \quad \Rightarrow  \quad(m,n) $$

$$ \text{ matrix } (m,n)  \quad +  -  *  / \quad (m,1) \quad \Rightarrow  \quad(m,n) $$

$$ \text{ matrix } (1,m)  \quad +  -  *  / \quad \text{Real Number} \quad \Rightarrow  \quad(1,m) $$

$$ \text{ matrix } (m,1)  \quad +  -  *  / \quad \text{Real Number} \quad \Rightarrow  \quad(m,1) $$
<br><br>

<hr>

(Example)
100g의 다양한 음식에 포함된 탄수화물, 단백질, 지방의 칼로리가 다음과 같을 때,탄수화물, 단백질, 지방으로부터의 칼로리가 각각 몇 % 인지를 계산하는 문제가 있다. 

| \  | Apples | Beef | Eggs | Potatoes |
|----|--------|------|------|----------|
|Carb| 56.0 | 0.0 | 4.4 | 68.0|
|Protein|1.2| 104.0 | 52.0 | 8.0|
|Fat | 1.8 | 135.0 | 99.0 | 0.9|

위의 계산을 명시적인 for-loop 를 사용하지 않고 할 수 있는가?

In [2]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

cal = A.sum(axis = 0)
print(cal)
percentage = 100 * A / cal
print(percentage)
print(A.shape, cal.shape, percentage.shape)

[ 59.  239.  155.4  76.9]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
(3, 4) (4,) (3, 4)
